/*
 * USART_Driver_Cfg.c
 *
 *  Created on: Oct 23, 2018
 *      Author: zsolt.balo
 */

#include "USART_Driver_Cfg.h"

/*Serial Communication Interface x - UART config*/
SERCOM_DRIVER_Register_Group* SERCOM_DRIVER_Registers[6] = 
{
    SERCOM_0_DRIVER_REG,		
    SERCOM_1_DRIVER_REG,
    SERCOM_2_DRIVER_REG,
    SERCOM_3_DRIVER_REG,
    SERCOM_4_DRIVER_REG,
	SERCOM_5_DRIVER_REG
};

USART_Driver_Setup_Type USART_CONF_SETUP[USART_DRIVER_INSTANCE_NUM]=
{
	{
		USART_DRIVER_0,
		9600,
		USART_DRIVER_8_bits,
		USART_DRIVER_PARITY_NONE,
		USART_DRIVER_PARITY_DEFAULT,
		USART_DRIVER_TRANSMIT_ENABLE,
		USART_DRIVER_TX_PINOUT_PAD2,
		USART_DRIVER_RECEIVE_ENABLE,
		USART_DRIVER_RX_PINOUT_PAD3,
		USART_DRIVER_STOPBIT_ONE,
		USART_DRIVER_16X_OVER_SAMPLING_FRACT,
	}
};

USART_Driver_Setup_Type* USART_SETUP = USART_CONF_SETUP;

