/*
 * HWCRC_Driver_Cfg.h
 *
 *  Created on: May 7, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_HWCRC_DRIVER_HWCRC_DRIVER_CFG_H_
#define DRIVERS_HWCRC_DRIVER_HWCRC_DRIVER_CFG_H_

#include "HWCRC_Driver.h"

#define HWCRC_DRIVER_ENABLE					OK
#define HWCRC_REVERSE_OUTPUT_DATA_EN		NOK
#define HWCRC_XOR_OUTPUT_DATA_EN			NOK
#define HWCRC_REVERSE_INPUT_DATA			HWCRC_BIT_ORDER_NOT_AFFECTED
#define HWCRC_POLYNOMIAL_SIZE               HWCRC_32_BIT_POLYNOMIAL
#define HWCRC_POLYNOMIAL               		0x04C11DB7
#define HWCRC_INIT_VALUE					0xFFFFFFFF


#endif /* DRIVERS_HWCRC_DRIVER_HWCRC_DRIVER_CFG_H_ */
